repos:
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black

- repo: local
  hooks:
    - id: run_tests
      name: run-tests
      entry: .\\run-tests.bat
      stages: [commit]
      language: script
