name: CI

on:
  push:
    branches: [main]

  pull_request:
    types: [opened]

  workflow_dispatch:

jobs:
  linter:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: pip install .'[dev]'

      - name: Run linter
        run: ruff check src/stuom

  tests_bash_shell:
    needs: linter
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        pydantic-version: ["~=2.6.0", "~=2.7.0", "~=2.8.0"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: pip install .'[dev]'

      - name: Install specific version of pydantic
        run: pip install pydantic${{ matrix.pydantic-version }}

      - name: Run tests
        run: pytest -s -vvvv -l --tb=long tests

  tests_win:
    needs: linter
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pip
        run: python -m pip install --user --upgrade pip

      - name: Install project
        run: pip install .[dev]

      - name: run tests
        run: pytest -s -vvvv -l --tb=long tests
